// Generated by scripts/emit_opencode.py from Agent Plugin 1.0 metadata.
// Skills are discovered through the static skills.paths config fragment.
const agentPluginAdapter = async () => ({});

export default agentPluginAdapter;
