#!/usr/bin/env python3
"""Emit a native OpenCode compatibility projection from an Agent Plugin 1.0 root."""

from __future__ import annotations

import argparse
import json
from pathlib import Path, PurePosixPath
from typing import Any


PLUGIN_SCHEMA = "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"
REMOTE_TRANSPORTS = {"http", "sse", "streamable-http"}


def read_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text())
    if not isinstance(data, dict):
        raise SystemExit(f"expected JSON object: {path}")
    return data


def relative_resource(value: str, *, field: str) -> str:
    path = PurePosixPath(value.removeprefix("./"))
    if path.is_absolute() or ".." in path.parts or not path.parts:
        raise SystemExit(f"{field} must stay below the plugin root: {value}")
    return path.as_posix().rstrip("/")


def opencode_mcp(entry: dict[str, Any], *, name: str) -> dict[str, Any]:
    transport = entry.get("type")
    enabled = entry.get("enabled", True)
    if transport in REMOTE_TRANSPORTS:
        if not isinstance(entry.get("url"), str):
            raise SystemExit(f"MCP server {name!r} is missing url")
        result: dict[str, Any] = {
            "type": "remote",
            "url": entry["url"],
            "enabled": enabled,
        }
        if "headers" in entry:
            result["headers"] = entry["headers"]
        return result
    if transport == "stdio":
        command = entry.get("command")
        if not isinstance(command, str) or not command:
            raise SystemExit(f"MCP server {name!r} is missing command")
        args = entry.get("args", [])
        if not isinstance(args, list) or not all(isinstance(item, str) for item in args):
            raise SystemExit(f"MCP server {name!r} has invalid args")
        result = {
            "type": "local",
            "command": [command, *args],
            "enabled": enabled,
        }
        environment = entry.get("env", entry.get("environment"))
        if environment is not None:
            result["environment"] = environment
        return result
    raise SystemExit(f"MCP server {name!r} uses unsupported transport: {transport!r}")


def generated_files(
    plugin_root: Path,
    *,
    package_name: str,
    includes: list[str],
    dependencies_from: Path | None,
) -> dict[Path, str]:
    manifest = read_json(plugin_root / "plugin.json")
    if manifest.get("$schema") != PLUGIN_SCHEMA:
        raise SystemExit(f"not an Agent Plugin 1.0 root: {plugin_root}")
    name = manifest.get("name")
    version = manifest.get("version")
    if not isinstance(name, str) or not isinstance(version, str):
        raise SystemExit("plugin.json must declare string name and version")

    # Agent Plugins 1.0 discovers components at fixed locations. A missing
    # component is valid, so MCP-only plugins must not need an empty skills tree.
    skills_path = "skills"
    skills_dir = plugin_root / skills_path
    if skills_dir.exists() and not skills_dir.is_dir():
        raise SystemExit(f"skills is not a directory: {skills_dir}")
    has_skills = skills_dir.is_dir()

    servers: dict[str, Any] = {}
    mcp_path = plugin_root / "mcp.json"
    if mcp_path.exists():
        mcp = read_json(mcp_path)
        if mcp.get("$schema") != "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json":
            raise SystemExit(f"unsupported Agent Plugin MCP schema: {mcp.get('$schema')!r}")
        raw_servers = mcp.get("mcpServers", {})
        if not isinstance(raw_servers, dict):
            raise SystemExit("mcp.json mcpServers must be an object")
        for server_name, entry in raw_servers.items():
            if not isinstance(server_name, str) or not isinstance(entry, dict):
                raise SystemExit("mcp.json contains an invalid server entry")
            servers[server_name] = opencode_mcp(entry, name=server_name)

    if servers:
        module = (
            "// Generated by scripts/emit_opencode.py from Agent Plugin 1.0 metadata.\n"
            f"const MCP_SERVERS = {json.dumps(servers, indent=2, ensure_ascii=False)};\n\n"
            "const agentPluginAdapter = async () => ({\n"
            "  config: async (config) => {\n"
            "    config.mcp ??= {};\n"
            "    for (const [name, entry] of Object.entries(MCP_SERVERS)) {\n"
            "      config.mcp[name] ??= entry;\n"
            "    }\n"
            "  },\n"
            "});\n\n"
            "export default agentPluginAdapter;\n"
        )
    else:
        module = (
            "// Generated by scripts/emit_opencode.py from Agent Plugin 1.0 metadata.\n"
            "// Skills are discovered through the static skills.paths config fragment.\n"
            "const agentPluginAdapter = async () => ({});\n\n"
            "export default agentPluginAdapter;\n"
        )

    files = ["opencode-plugin/", "plugin.json"]
    if has_skills:
        files.append(f"{skills_path}/")
    if mcp_path.exists():
        files.append("mcp.json")
    for value in includes:
        resource = relative_resource(value, field="include")
        if not (plugin_root / resource).exists():
            raise SystemExit(f"included resource does not exist: {plugin_root / resource}")
        files.append(resource + ("/" if (plugin_root / resource).is_dir() else ""))
    files = list(dict.fromkeys(files))

    package: dict[str, Any] = {
        "name": package_name,
        "version": version,
        "description": f"OpenCode compatibility package for {manifest.get('description', name)}",
        "main": "opencode-plugin/index.js",
        "exports": {".": "./opencode-plugin/index.js"},
        "files": files,
        "keywords": list(dict.fromkeys(["opencode", "opencode-plugin", "agent-plugin", name])),
        "license": manifest.get("license", "UNLICENSED"),
        "peerDependencies": {"@opencode-ai/plugin": ">=1.0.0"},
        "peerDependenciesMeta": {"@opencode-ai/plugin": {"optional": True}},
    }
    for key in ("author", "homepage", "repository"):
        if key in manifest:
            package[key] = manifest[key]
    if dependencies_from is not None:
        dependency_manifest = read_json(dependencies_from)
        dependencies = dependency_manifest.get("dependencies", {})
        if not isinstance(dependencies, dict):
            raise SystemExit(f"dependencies must be an object: {dependencies_from}")
        if dependencies:
            package["dependencies"] = dependencies

    fragment: dict[str, Any] = {
        "$schema": "https://opencode.ai/config.json",
        "plugin": [package_name],
    }
    if has_skills:
        fragment["skills"] = {"paths": [f"node_modules/{package_name}/{skills_path}"]}
    readme = f"""# {package_name}

Generated OpenCode compatibility package for the `{name}` Agent Plugin 1.0 bundle.

Install the package in the project, then merge `opencode.json` into the project
OpenCode configuration. OpenCode loads MCP servers through the native plugin hook
and discovers skills through the static `skills.paths` entry.
"""
    return {
        plugin_root / "package.json": json.dumps(package, indent=2, ensure_ascii=False) + "\n",
        plugin_root / "opencode-plugin/package.json": json.dumps(
            {"private": True, "type": "module"}, indent=2
        )
        + "\n",
        plugin_root / "opencode-plugin/index.js": module,
        plugin_root / "opencode-plugin/opencode.json": json.dumps(fragment, indent=2) + "\n",
        plugin_root / "opencode-plugin/README.md": readme,
    }


def emit(
    plugin_root: Path,
    *,
    package_name: str,
    includes: list[str] | None = None,
    dependencies_from: Path | None = None,
    check: bool = False,
) -> None:
    plugin_root = plugin_root.resolve()
    outputs = generated_files(
        plugin_root,
        package_name=package_name,
        includes=includes or [],
        dependencies_from=dependencies_from.resolve() if dependencies_from else None,
    )
    drift = [path for path, content in outputs.items() if not path.exists() or path.read_text() != content]
    if check:
        if drift:
            raise SystemExit("OpenCode projection drift: " + ", ".join(str(path) for path in drift))
        return
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("plugin_root", type=Path)
    parser.add_argument("--package-name", required=True)
    parser.add_argument("--include", action="append", default=[])
    parser.add_argument("--dependencies-from", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    emit(
        args.plugin_root,
        package_name=args.package_name,
        includes=args.include,
        dependencies_from=args.dependencies_from,
        check=args.check,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
